/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eso' at '04.11.15 14:45' with Gradle 2.6
 *
 * @author eso, @date 04.11.15 14:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
